services:
  pushover-bridge-service:
    restart: always
    user: 2100:2100
    image: oitc/acs.pushover-bridge-service:latest
    environment:
      MQTT_SERVER: test.mosquitto.org
      MQTT_PORT: 8883
      MQTT_PROTOCOL_VERSION: 5
      MQTT_TLS: true
      MQTT_CACERT_FILE: /etc/ssl/certs/ca-certificates.crt
      MQTT_TLS_INSECURE: false
      MQTT_CLIENT_ID: c27c9da3-ac39-47f2-bf03-48753d1ab3e7
      MQTT_USERNAME: acs.pushover-bridge-service
      #MQTT_PASSWORD: myMQTTPassword
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      MQTT_TOPIC_ACS_STATUS: location/oitc-acs/general/status
      MQTT_TOPIC_DOOR_ACCESS: location/oitc-acs/entrypoints/+/access
      #PUSHOVER_APP_TOKEN: myPushoverAppToke
      PUSHOVER_APP_TOKEN_FILE: /run/secrets/pushover_app_token
      #PUSHOVER_USER_KEY: myPushoverUserKey
      PUSHOVER_USER_KEY_FILE: /run/secrets/pushover_user_key
      PROMETHEUS_LISTENER_ADDR: 0.0.0.0
      PROMETHEUS_LISTENER_PORT: 8080
      TZ: Europe/Berlin
    ports:
      - "8080:8080"
    secrets:
      - mqtt_password
      - pushover_app_token
      - pushover_user_key

secrets:
  mqtt_password:
    file: /srv/docker/acs.pushover-bridge-service/secrets/mqtt_password
  pushover_app_token:
    file: /srv/docker/acs.pushover-bridge-service/secrets/pushover_app_token
  pushover_user_key:
    file: /srv/docker/acs.pushover-bridge-service/secrets/pushover_user_key
